FROM ubuntu

COPY . /app

RUN apt-get update && apt-get install -y \
    make \
    python3 \
    python3-pip

WORKDIR /app

ARG var_url='http://host.docker.internal:8000'
ENV BASE_URL=$var_url

RUN make install-tests
RUN make run-tests
